name: "Gitleaks Full Secret Scan"

on:
  workflow_dispatch:

jobs:
  gitleaks-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo (celá história)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Fetch all branches
        run: git fetch --all

      - name: Run Gitleaks (full repo – all branches & commits)
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITLEAKS_LICENSE: ${{ secrets.GITLEAKS_LICENSE }}
        with:
          log_opts: "--all --full-history"
